services:

  mysql:
    image: mysql:8.0
    container_name: finguard-mysql
    restart: unless-stopped
    env_file:
      - /etc/finguard.env
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: finguard-zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: finguard-kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  app:
    image: finguard-risk-service-app:${IMAGE_TAG}
    restart: unless-stopped
    depends_on:
      - mysql
      - kafka
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - /etc/finguard.env
    environment:
      SPRING_R2DBC_URL: r2dbc:mysql://mysql:3306/finguard
      KAFKA_HOST: kafka:9092
    deploy:
      resources:
        limits:
          memory: 2g

volumes:
  mysql_data: