spring:
  application:
    name: finguard-risk-service
  main:
    web-application-type: reactive
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
  sql:
    init:
      mode: always

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: ${REDIS_SSL_ENABLED}
  kafka:
    bootstrap-servers: ${KAFKA_HOST}

jwt:
  keyId: ${JWT_KEY_ID}
  secret: ${JWT_SECRET}

#google:
#  client-id: ${GOOGLE_CLIENT_ID}