spring:
  application:
    name: finguard-risk-service
  main:
    web-application-type: reactive
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: ${KAFKA_HOST}

jwt:
  keyId: ${JWT_KEY_ID}
  secret: ${JWT_SECRET}

google:
  android:
    client-id: ${GOOGLE_ANDROID_CLIENT_ID}
  ios:
    client-id: ${GOOGLE_IOS_CLIENT_ID}
  service-account-path: ${GOOGLE_SERVICE_ACCOUNT_PATH}

apple:
  bundle-id: ${APPLE_BUNDLE_ID}

android:
  package: ${ANDROID_PACKAGE}

subscription:
  max-skew: ${SUBSCRIPTION_MAX_SKEW}
  
security:
  allowedPublicPaths: ${ALLOWED_PUBLIC_PATHS}